POST http://localhost:5000/api/product/ HTTP/1.1
Content-Type: application/json

{
    "name":"Carrot",
        "cost":45,
     "image":"https://media.istockphoto.com/id/184276818/uk/%D1%84%D0%BE%D1%82%D0%BE/%D1%87%D0%B5%D1%80%D0%B2%D0%BE%D0%BD%D0%B5-%D1%8F%D0%B1%D0%BB%D1%83%D0%BA%D0%BE.jpg?s=612x612&w=0&k=20&c=b4rwqHVUrtfedn1Xjfnpkqn-OX3ROs3Az34WWp29BcA="
}